version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven using Docker"
  pre_build:
    commands:
      - cd fitmymacrosLambda
      - echo "Executing pre-build commands"
  build:
    commands:
      - echo "Compiling the Maven project"
      - docker run --rm -v $(pwd):/usr/src/mymaven -w /usr/src/mymaven maven:3.8.4 mvn clean compile assembly:single -DskipTests=false
      - sam deploy --template-file template.yaml --stack-name openailambda-stack --capabilities CAPABILITY_IAM --s3-bucket fit-my-macros
  post_build:
    commands:
      - echo "Updating API Gateway to use the lambda alias 'dev' for the 'dev' stage"
      - aws apigateway update-stage --rest-api-id MyApi --stage-name dev --patch-operations op=replace,path=/deploymentId,value=MyApidevStage
      - aws apigateway update-integration --rest-api-id FitMyMacrosApi --resource-id 'recipes' --http-method GET --patch-operations op=replace,path=/uri,value="arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/{arn:aws:lambda:eu-west-3:829527069263:function:openailambda-stack-OpenAILambdaFunction-KAbV8SPzdNXM}:dev/invocations" --stage-name dev

