version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11 # Specify the Java runtime version
    commands:
      - echo "Installing Maven"
      - apt-get update && apt-get install -y maven # Install Maven if it's not already available
  pre_build:
    commands:
      - echo "Executing pre-build commands"
  build:
    commands:
      - echo "Compiling the Maven project"
      - mvn clean install -DskipTests=false # Compile the project and run tests
  post_build:
    commands:
      - echo "Executing post-build commands"
      - mv target/my-project.jar ../ # Move the built artifact to a directory accessible by CodeDeploy

artifacts:
  files:
    - my-project.jar # Specify the artifact to be passed to the next stage