AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  OpenAILambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.fitmymacros.OpenAILambda::handleRequest
      Runtime: java11
      CodeUri: target/openAILambda-jar-with-dependencies.jar
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: '*'
      MemorySize: 512
      Timeout: 30
  OpenAILambdaAlias:
     Type: AWS::Lambda::Alias
     DependsOn: OpenAILambdaFunction
     Properties:
      FunctionName: !Ref OpenAILambdaFunction.Arn
      FunctionVersion: !GetAtt OpenAILambdaFunction.Version
      Name: dev  

  MyApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: '2.0'
        info:
          title: 'FitMyMacrosApi'
        paths:
          /recipes:
            get:
              responses:
                '200':
                  description: 'Successful response'
                '400':
                  description: 'Error' 
              x-amazon-apigateway-integration:
                httpMethod: GET
                type: aws_proxy
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OpenAILambdaAlias.Arn}:dev/invocations'
