version: 0.0
os: linux
files:
  - source: fitmymacrosLambda/target/openAILambda.jar
    destination: /var/task/openAILambda.jar
hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
