AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.fitmymacros.OpenAILambda::handleRequest
      Runtime: java11
      CodeUri: fitmymacros-1.0-SNAPSHOT.jar
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          OPENAI_API_KEY: 'YOUR_DEFAULT_API_KEY_VALUE'

  MyApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: '2.0'
        info:
          title: 'My API'
        paths:
          /myresource:
            get:
              x-amazon-apigateway-integration:
                type: aws_proxy
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations'
